
def generate_sample_note(transcript: str) -> dict:
    cleaned = transcript.strip()

    if not cleaned:
        raise ValueError("Transcript cannot be empty")

    return {
        "note_type": "demo",
        "chief_complaint": "Requires clinician review",
        "clinical_note": cleaned,
        "assessment": "Not generated by the demo backend",
        "plan": "Clinician review required",
        "disclaimer": (
            "Demonstration output only. Verify all information before "
            "clinical use. This is not a diagnosis or treatment recommendation."
        )
    }

def generate_sample_note(transcript: str) -> dict:
    cleaned = transcript.strip()

    if not cleaned:
        raise ValueError("Transcript cannot be empty")

    return {
        "note_type": "demo",
        "chief_complaint": "Requires clinician review",
        "clinical_note": cleaned,
        "assessment": "Not generated by the demo backend",
        "plan": "Clinician review required",
        "disclaimer": (
            "Demonstration output only. Verify all information before "
            "clinical use. This is not a diagnosis or treatment recommendation."
        ),
    }